[project]
name = "opencvgame"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mediapipe>=0.10.18",
    "opencv-python>=4.10.0.84",
    "protobuf>=4.25.5",
    "pygame>=2.6.1",
]
